apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db-mariadb-container
      image: mariadb:latest
      ports:
        - containerPort: 3306
          #env:
          #  - name: "CUSTOM_CONFIG"
          #    value: "dont use configmap"
          #  - name: "MARIADB_USER"
          #    valueFrom:
          #      configMapKeyRef:
          #        name: configmap
          #        key: MARIADB_USER
      envFrom:
        - configMapRef:
            name: configmap
